name: Training Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        cache: 'pip'
    - run: pip install -r requirements.txt

    - name: Test environment
      run: python testEnvironment.py

    - name: Data Ingestion
      run: python src/pipeline/stage01_data_ingestion.py

    - name: Data Pre Processing
      run: python src/pipeline/stage02_data_processing.py

    - name: Model Training
      run: python src/pipeline/stage03_model_training.py

  post:
    needs: setup
    runs-on: ubuntu-latest
    
    steps:
    - name: Notify success
      if: success()
      run: |
        echo "✅ Training Pipeline completed successfully!"
        echo "🚀 Triggering deployment job..."
        # Trigger another GitHub Action workflow if needed

    - name: Notify failure
      if: failure()
      run: echo "❌ Pipeline failed. Check logs."
